# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 47561abd6d68600f15a0a72fcd92c1c580695ab55e17faf4d32cc0264f1ce9c2f46c72c8b0e751427c065039ff0769fb7564074f50c11812338d5f96d026d64d

test:
  secret_key_base: 3fa8241e74cdaf2fc918b3788a3975fe41e7b63b7974cd73372c741c2105ba71ed09ed75d764b11b36bafa868de96d24ddf574f25e1ee24fcdbcb87d5c6b997d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
